### ISSUE TITLE
disk space check and proper error

### ISSUE THREAD

**Issue by dreacot** [planetdecred/dcrios#867] opened 2021-10-26 10:57 UTC
A user reported an error of
"another process is using this Badger database"
and then later reported it was due to low disk space. We can check for this condition to properly alert the user.

Related to https://github.com/planetdecred/dcrandroid/issues/233

**Comment by monsa00** [comment] 2021-12-07 19:40
This looks like a duplicate of [#458](https://github.com/planetdecred/dcrios/issues/458)

**Closed** 2021-12-29 11:57 UTC
Labels: enhancement
